"""
ATLAS Morning Digest — Daily spoken briefing in the JARVIS voice

Briefing flow (spoken + displayed on feed panel):
  "Good morning Boss. It is [day], [date]."
  "Currently [temp] and [condition] in your area."
  "You have [N] events today. First: [event] at [time]."
  "Here are your top headlines." → 3 headlines with summary
  "You have [N] tasks pending. Most urgent: [task]."
  "That is your briefing, Boss. Shall I elaborate?"

Script is generated by Groq at night and cached in memory/digest_cache.json
so it plays instantly in the morning.

Voice commands:
  "atlas morning briefing"     → trigger now
  "atlas skip to news"         → jump to news section
  "atlas elaborate on that"    → expand last briefing item
"""

from __future__ import annotations

import json
import logging
import os
import platform
import subprocess
import threading
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Callable, Optional

import requests

log = logging.getLogger(__name__)

_CACHE_PATH = Path(__file__).resolve().parent / "memory" / "digest_cache.json"


class DigestModule:
    """
    Morning briefing generator and playback for ATLAS.

    Usage in main.py:
        digest = DigestModule(config, brain=brain)
        digest.set_speak_callback(vm.speak)
        digest.set_feed_callback(window.feed_panel.add_feed_item)
        digest.start()          # starts scheduler
        digest.stop()
    """

    _SECTIONS = ["greeting", "weather", "calendar", "news", "tasks", "closing"]

    def __init__(self, config: dict, brain=None):
        self._cfg          = config
        self._brain        = brain
        self._speak_cb: Optional[Callable[[str], None]]      = None
        self._feed_cb:  Optional[Callable[[str, str], None]] = None
        self._state_cb: Optional[Callable[[str], None]]      = None

        briefing_time = config.get("morning_briefing_time", "08:00")
        try:
            h, m = briefing_time.split(":")
            self._briefing_hour   = int(h)
            self._briefing_minute = int(m)
        except Exception:
            self._briefing_hour   = 8
            self._briefing_minute = 0

        self._stop_event     = threading.Event()
        self._script: Optional[dict] = None  # cached briefing sections
        self._last_elaborated_section = ""
        self._current_section_idx     = 0
        self._scheduler_thread: Optional[threading.Thread] = None
        self._pre_gen_thread:   Optional[threading.Thread] = None

        self._load_cache()

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self):
        self._scheduler_thread = threading.Thread(
            target=self._scheduler_loop, daemon=True, name="atlas-digest"
        )
        self._scheduler_thread.start()

        # Pre-generate tonight's briefing in the background
        self._pre_gen_thread = threading.Thread(
            target=self._pre_generate_if_needed, daemon=True, name="atlas-digest-gen"
        )
        self._pre_gen_thread.start()
        log.info("Digest module started (briefing at %02d:%02d).",
                 self._briefing_hour, self._briefing_minute)

    def stop(self):
        self._stop_event.set()

    def set_speak_callback(self, cb: Callable[[str], None]):
        self._speak_cb = cb

    def set_feed_callback(self, cb: Callable[[str, str], None]):
        self._feed_cb = cb

    def set_state_callback(self, cb: Callable[[str], None]):
        self._state_cb = cb

    # ── Voice command handler ─────────────────────────────────────────────────

    def handle(self, text: str) -> Optional[str]:
        lower = text.lower().strip()

        if any(p in lower for p in ("atlas morning briefing", "atlas briefing",
                                     "give me my briefing", "morning briefing")):
            threading.Thread(target=self._play_briefing, daemon=True).start()
            return "Starting your morning briefing, Boss."

        if any(p in lower for p in ("atlas skip to news", "skip to news",
                                     "atlas news section")):
            self._current_section_idx = self._SECTIONS.index("news")
            threading.Thread(target=self._play_from_section, daemon=True).start()
            return "Jumping to the news section."

        if any(p in lower for p in ("atlas elaborate on that", "elaborate on that",
                                     "atlas tell me more about that",
                                     "can you expand on that")):
            return self._elaborate()

        return None

    # ── Briefing playback ─────────────────────────────────────────────────────

    def _play_briefing(self):
        self._current_section_idx = 0
        self._play_from_section()

    def _play_from_section(self):
        if not self._script:
            self._generate_briefing_now()

        if not self._script:
            msg = "I couldn't generate a briefing right now, Boss."
            self._speak(msg)
            return

        for i in range(self._current_section_idx, len(self._SECTIONS)):
            section = self._SECTIONS[i]
            text    = self._script.get(section, "")
            if text:
                self._last_elaborated_section = section
                self._feed("briefing", text)
                self._speak(text)

    def _speak(self, text: str):
        if self._speak_cb:
            self._speak_cb(text)
        else:
            log.info("[DIGEST SPEAK] %s", text)

    def _feed(self, category: str, text: str):
        if self._feed_cb:
            self._feed_cb(category, text)

    def _elaborate(self) -> str:
        if not self._last_elaborated_section or not self._brain:
            return "There's nothing to elaborate on right now."

        short = self._script.get(self._last_elaborated_section, "") if self._script else ""
        if not short:
            return "I don't have details for that section."

        prompt = (
            f"Expand on this morning briefing section in 3-5 sentences for voice. "
            f"Plain text only.\n\nSection: {short}"
        )
        try:
            return self._brain.ask(prompt)
        except Exception:
            return short

    # ── Script generation ─────────────────────────────────────────────────────

    def _generate_briefing_now(self):
        """Generate and cache today's briefing script synchronously."""
        log.info("Generating morning briefing script …")
        try:
            sections = {}
            sections["greeting"] = self._gen_greeting()
            sections["weather"]  = self._gen_weather()
            sections["calendar"] = self._gen_calendar()
            sections["news"]     = self._gen_news()
            sections["tasks"]    = self._gen_tasks()
            sections["closing"]  = "That is your briefing, Boss. Shall I elaborate on anything?"
            self._script = sections
            self._save_cache()
            log.info("Morning briefing script ready.")
        except Exception as exc:
            log.error("Briefing generation error: %s", exc)

    def _pre_generate_if_needed(self):
        """Generate tonight's briefing if not already cached for today."""
        cached_date = (self._script or {}).get("_date")
        if cached_date == date.today().isoformat():
            log.info("Digest: today's briefing already cached.")
            return
        self._generate_briefing_now()

    def _gen_greeting(self) -> str:
        now = datetime.now()
        day = now.strftime("%A")
        dt  = now.strftime("%B %d")
        hour = now.hour
        greeting = "Good morning" if hour < 12 else ("Good afternoon" if hour < 17 else "Good evening")
        return f"{greeting}, Boss. It is {day}, {dt}."

    def _gen_weather(self) -> str:
        config = self._cfg
        lat    = config.get("location_lat", 51.5)
        lon    = config.get("location_lon", -0.1)
        try:
            url    = "https://api.open-meteo.com/v1/forecast"
            params = {
                "latitude":        lat,
                "longitude":       lon,
                "current_weather": True,
                "timezone":        "auto",
            }
            r  = requests.get(url, params=params, timeout=8)
            cw = r.json().get("current_weather", {})
            temp = cw.get("temperature", "?")
            code = int(cw.get("weathercode", 0))
            cond = _wmo(code)
            return f"Currently {temp} degrees and {cond} in your area."
        except Exception:
            return "Weather data is unavailable right now."

    def _gen_calendar(self) -> str:
        if platform.system() != "Darwin":
            return ""
        script = '''
tell application "Calendar"
    set todayEvents to {}
    set theDate to current date
    set startOfDay to theDate - (time of theDate)
    set endOfDay to startOfDay + (23 * hours) + (59 * minutes)
    repeat with cal in calendars
        repeat with ev in (events of cal whose start date >= startOfDay and start date <= endOfDay)
            set evTitle to summary of ev
            set evStart to start date of ev
            set timeStr to (time string of evStart)
            set end of todayEvents to (evTitle & " at " & timeStr)
        end repeat
    end repeat
    return todayEvents
end tell
'''
        try:
            out = subprocess.run(
                ["osascript", "-e", script],
                capture_output=True, text=True, timeout=10
            ).stdout.strip()
            events = [e.strip() for e in out.split(",") if e.strip()] if out else []
            if not events:
                return "You have no calendar events today."
            first  = events[0]
            return (f"You have {len(events)} events today. "
                    f"First up: {first}.")
        except Exception:
            return ""

    def _gen_news(self) -> str:
        topics = self._cfg.get("news_topics", ["technology", "world"])
        try:
            from ddgs import DDGS
            headlines = []
            with DDGS() as ddgs:
                for topic in topics[:1]:
                    for r in ddgs.news(topic, max_results=3):
                        headlines.append(r.get("title", ""))

            if not headlines:
                return ""

            items = ". Next: ".join(headlines[:3])
            return f"Here are your top headlines. {items}."
        except Exception:
            return ""

    def _gen_tasks(self) -> str:
        try:
            path = Path(__file__).resolve().parent / "memory" / "reminders.json"
            if not path.exists():
                return ""
            reminders = json.loads(path.read_text(encoding="utf-8"))
            active = [r for r in reminders if not r.get("done")]
            if not active:
                return "You have no pending tasks."
            most_urgent = active[0]["text"]
            return (f"You have {len(active)} pending tasks. "
                    f"Most urgent: {most_urgent}.")
        except Exception:
            return ""

    # ── Scheduler ─────────────────────────────────────────────────────────────

    def _scheduler_loop(self):
        while not self._stop_event.is_set():
            self._stop_event.wait(30)  # check every 30 s
            if self._stop_event.is_set():
                break

            now = datetime.now()
            if (now.hour == self._briefing_hour
                    and now.minute == self._briefing_minute
                    and now.second < 30):
                log.info("Scheduled morning briefing triggered.")
                threading.Thread(target=self._play_briefing, daemon=True).start()
                self._stop_event.wait(90)  # avoid double-trigger within the minute

    # ── Cache ─────────────────────────────────────────────────────────────────

    def _load_cache(self):
        try:
            if _CACHE_PATH.exists():
                data = json.loads(_CACHE_PATH.read_text(encoding="utf-8"))
                if data.get("_date") == date.today().isoformat():
                    self._script = data
                    log.info("Digest: loaded today's cached briefing.")
        except Exception as exc:
            log.debug("Digest cache load failed: %s", exc)

    def _save_cache(self):
        try:
            _CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
            data = dict(self._script or {})
            data["_date"] = date.today().isoformat()
            _CACHE_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except Exception as exc:
            log.debug("Digest cache save failed: %s", exc)


def _wmo(code: int) -> str:
    m = {
        0: "clear", 1: "mainly clear", 2: "partly cloudy", 3: "overcast",
        45: "foggy", 51: "drizzling", 61: "raining", 71: "snowing",
        80: "showery", 95: "stormy",
    }
    return m.get(code, "mixed")
